'''
Created on Oct 11, 2018


This is a test suite of the DPM Regression Test, include an array of test cases, in the array, the cases will run in sequence.
If you want to add/remove some cases, just add/remove them on the tests array.

To add a test case, after add the element in the tests array, you should create a method in the DPMRegression class, the mathod should
start with "test_case_***".

@author: mayijie
'''

import unittest
import time
from Reg_unitTest import DPMRegression
from Reg_HTMLTestRunner import HTMLTestRunner

if __name__ == '__main__':
    #HTMLTestRunner.main()
    
    suite = unittest.TestSuite()
    
    # the sequence is matter, it's the order the cases execute
    tests = [DPMRegression("test_case_CreatePartition"),
             #DPMRegression("test_case_AddVNic"),
             #DPMRegression("test_case_AttachFCPStorageGroup"),
             DPMRegression("test_case_DynamicChangePartitionResource"),
             DPMRegression("test_case_ModifyFCPStorageGroup"),
             DPMRegression("test_case_DetachFCPStorageGroup"),
             DPMRegression("test_case_AttachFICONStorageGroup"),
             DPMRegression("test_case_DetachFICONStorageGroup")
             ]
    suite.addTests(tests)
    
    # record the logs to the HTML log file
    fileName = 'HTMLReport_' + time.strftime("%Y%m%d-%H%M%S", time.localtime()) + ".html"
    with open(fileName, 'wb') as fp:
        runner = HTMLTestRunner(stream = fp,
                                title = 'Regression Test Report',
                                description = 'Generated by HTMLTestRunner.',
                                verbosity = 2
                                )
        runner.run(suite)